### Convolução usando Pytorch

Veremos em detalhe como realizar convolução usando Pytorch e como funciona a camada convolucional

In [15]:
import torch
from torch import nn
import torch.nn.functional as F

# Sinal
x = torch.tensor([5, 4, 8, 7, 9, 3, 6], dtype = torch.float32)

# Filtro
weight = torch.tensor([1, 2, 3], dtype = torch.float32)

# Tamanho do filtro
# ks: kernel size
ks = len(weight)

# Redimensiona o sinal para o tamanho 1x1xlen(x). Ou seja, um batch contendo um único sinal, 
# e esse sinal possui um único canal
x = x.reshape(1, 1, len(x))

# Redimensiona o filtro. O primeiro valor 1 possui um significado diferente do que
# no caso do sinal. Depois será explicado.
weight = weight.reshape(1, 1, ks)

# Realiza a convolução
y = F.conv1d(x, weight)
y.shape

torch.Size([1, 1, 5])

O tamanho da entrada é 7 e da saída é 5. Isso porque o Pytorch realiza a convolução apenas nas posições que não necessitam de preenchimento de borda. Mas modificar o tamanho do resultado é indesejável. 

É muito comum realizarmos a convolução com padding para manter o tamanho do sinal:

In [16]:
# padding = ks//2 garante que a saída sempre terá o mesmo tamanho que a entrada
# é usado para evitar que o sinal de saída seja menor que a entrada
y = F.conv1d(x, weight, padding = ks//2)
print(y.shape)

torch.Size([1, 1, 7])


Dado o sinal [5, 4, 8, 7, 9, 3, 6] e filtro [1,2,3], nossa saída deve ser:

* y[0] = 1\*0 + 2\*5 + 3\*4 = 22
* y[1] = 1\*5 + 2\*4 + 3\*8 = 37
* ...
* y[6] = 1\*3 + 2\*6 + 3\*0 = 15

Note que a função realiza a correlação-cruzada, e não a convolução. Mas para redes neurais isso não importa.

In [17]:
print(y)

tensor([[[22., 37., 41., 49., 34., 33., 15.]]])


Em redes neurais a convolução possui o conceito de bias, que é simplesmente um valor constante que é adicionado ao resultado:

In [18]:
bias = torch.tensor([5.0])
# Adiciona o valor 5 a cada elemento do resultado da convolução
y_bias = F.conv1d(x, weight, padding = ks//2, bias = bias)
print(y_bias)
print(torch.allclose(y + bias, y_bias))

tensor([[[27., 42., 46., 54., 39., 38., 20.]]])
True


### Camada de convolução

In [19]:
# A entrada terá 1 canal, queremos apenas 1 canal de saída. O tamanho do filtro é ks, o 
# padding é metade do tamanho do filtro e a camada não terá bias
conv = nn.Conv1d(in_channels = 1,
                 out_channels = 1,
                 kernel_size = ks, 
                 padding = ks // 2, 
                 bias = False)
y = conv(x)
print(y)

tensor([[[-3.9199, -4.6784, -6.3966, -6.4905, -5.4768, -3.4029, -3.0002]]],
       grad_fn=<ConvolutionBackward0>)


Uma camada de convolução consiste em um filtro possuindo valores aleatórios. Esse filtro possui o parâmetro requires_grad=True por padrão. Podemos alterar os valores do filtro se quisermos:

In [20]:
print(conv.weight.shape)
print(conv.weight)

with torch.no_grad():
    conv.weight[:] = weight

# Mesmo resultado que a convolução que fizemos antes:
conv(x)

torch.Size([1, 1, 3])
Parameter containing:
tensor([[[ 0.0202, -0.5101, -0.3423]]], requires_grad=True)


tensor([[[22., 37., 41., 49., 34., 33., 15.]]], grad_fn=<ConvolutionBackward0>)

### Relação entre convolução e combinação linear

Uma convolução nada mais é do que uma combinação linear com menos parâmetros

In [21]:
# Matriz de convolução. Cada linha representa uma posição do kernel. Por exemplo,
# a linha 0 fará a operação 2*x[0]+3*x[1]+0*x[2]+...
matrix = torch.tensor([
    [2, 3, 0, 0, 0, 0, 0],
    [1, 2, 3, 0, 0, 0, 0],
    [0, 1, 2, 3, 0, 0, 0],
    [0, 0, 1, 2, 3, 0, 0],
    [0, 0, 0, 1, 2, 3, 0],
    [0, 0, 0, 0, 1, 2, 3],
    [0, 0, 0, 0, 0, 1, 2]
], dtype = torch.float32)

F.linear(x, matrix)

tensor([[[22., 37., 41., 49., 34., 33., 15.]]])

Acima temos uma matrix 7x7 que recebe 7 atributos de entrada e gera 7 atributos de saída. Mas a combinação linear dos atributos de entrada sempre envolvem apenas 3 parâmetros.

### Convolução com mais de um canal

In [22]:
# Batch contendo um sinal de tamanho 7 e com 4 canais
x = torch.rand(size=(1,4,7))

# Camada que recebe sinal com 4 canais e gera um sinal com 5 canais.
conv = nn.Conv1d(in_channels = 4, 
                 out_channels = 5, 
                 kernel_size = ks, 
                 padding = ks // 2, 
                 bias = False)

y = conv(x)
print('x\n',x)
# Saída possui tamanho 1x5x7
print('y\n',y)

x
 tensor([[[0.4027, 0.1971, 0.2992, 0.7474, 0.8890, 0.2707, 0.9824],
         [0.8133, 0.4863, 0.4015, 0.5694, 0.2748, 0.1433, 0.1710],
         [0.0662, 0.3610, 0.0511, 0.9595, 0.3858, 0.3460, 0.9012],
         [0.8778, 0.1816, 0.6554, 0.2091, 0.1478, 0.5182, 0.5321]]])
y
 tensor([[[ 0.2347,  0.2551,  0.1695,  0.4959,  0.3485,  0.1347,  0.3603],
         [ 0.4626,  0.2952,  0.2327,  0.2062,  0.0860,  0.0189,  0.2314],
         [-0.3748, -0.0821, -0.2687, -0.5344, -0.3121, -0.0604, -0.7165],
         [-0.5579, -0.2040, -0.4123,  0.0645,  0.0962, -0.1094,  0.1056],
         [-0.2092, -0.0247,  0.1635, -0.0399,  0.3188,  0.2694, -0.0553]]],
       grad_fn=<ConvolutionBackward0>)


* O **número de canais de saída** define o **número de filtros** que serão utilizados na camada de convolução. No nosso caso, temos 5 filtros
* Cada filtro possui **tamanho espacial ks**
* Cada filtro possui **profundidade 4**, pois o sinal de entrada possui 4 canais.
* Portanto, temos 5 filtros de tamanho 4 x ks cada
* Portanto, o tamanho do tensor .weight da camada de convolução possui tamanho 5 x 4 x ks

In [23]:
conv.weight.shape

torch.Size([5, 4, 3])

In [24]:
# Filtro 1 da camada
filtro1 = conv.weight[0]
# Região do sinal que corresponde quando o filtro está na posição 1
regiao = x[0,:,0:3]
# Resultado da convolução para esse ponto específico
res = (filtro1*regiao).sum()
# comparação do resultado
print(torch.allclose(y[0,0,1], res))

True


### Outros parâmetros da convolução

#### Stride
Stride define a quantidade de deslocamento do filtro para cada posição na qual a convolução será calculada

In [25]:
x = torch.tensor([5, 4, 8, 7, 9, 3, 6], dtype=torch.float32)
weight = torch.tensor([1, 2, 3], dtype=torch.float32)
x = x.reshape(1,1,len(x))
weight = weight.reshape(1,1,len(weight))

# Faz o filtro deslocar duas posições ao invés de deslocar uma posição por vez
y = F.conv1d(x, weight, stride=2)
print(y)

tensor([[[37., 49., 33.]]])


In [26]:
# O resultado de stride=2 é equivalente a indexar a saída de stride=1 pulando 2 índices
yt = F.conv1d(x, weight, stride=1)
print(torch.allclose(y, yt[0,0,::2]))

True


#### Dilatação

Dilatação consiste em aumentar o tamanho do filtro sem aumentar o número de parâmetros

In [27]:
y = F.conv1d(x, weight, dilation=2)
print(y)

tensor([[[48., 27., 44.]]])


In [28]:
# dilatação=2 é equivalente a inserir 0 entre os valores do filtro
wt = torch.tensor([1, 0, 2, 0, 3], dtype=torch.float32).reshape(1,1,-1)
yt = F.conv1d(x, wt, dilation=1)
print(torch.allclose(y, yt))

True
